#pragma once
struct ToAccIdEl;
struct WartEl;
struct QuoteEl;
struct AmountEl;
struct NonzeroAmountEl;
struct SharesEl;
struct NonzeroSharesEl;
struct BaseEl;
struct OriginAccIdEl;
struct CancelNonceEl;
struct CancelHeightEl;
struct PinNonceEl;
struct CompactFeeEl;
struct AssetSupplyEl;
struct AssetNameEl;
struct SignatureEl;
struct LimitPriceEl;
struct BuyEl;
